artifacts_root: artifacts

# root directory for data ingestion artifacts 
data_ingestion:
  root_dir: artifacts/data_ingestion    
  source_URL: https://drive.google.com/file/d/1eB4WPSWYFWgXmkwGteICvvum9eGYHUFe/view?usp=sharing
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion